name: Validate Project Structure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install Required Tools
      run: sudo apt-get update && sudo apt-get install -y tree python3

    - name: List Project Structure
      run: tree --dirsfirst -L 2

    - name: Validate Python Scripts
      run: python3 src/setup_wizard.py
