name: Validate Project Structure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-structure:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: List Project Directory Structure
      run: |
        echo "Validating project folder structure..."
        tree --dirsfirst -L 3
